# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ChippyCheckerEditor
                                 A QGIS plugin
 This a plugin to edit vector layer with chips as background.

 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-07-04
        copyright            : (C) 2022 by Development Seed
        email                : ruben@developmentseed.org
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ChippyCheckerEditor class from file ChippyCheckerEditor.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .chippy_checker_editor import ChippyCheckerEditor
    return ChippyCheckerEditor(iface)
